### ISSUE TITLE
[FE]  isbn이 똑같은 책이 여러 번 나옵니다.

### ISSUE THREAD

**Issue by gitubanana** [leechan02/Bookmoeum#46]
## ⚠️ 어떤 버그인가요 ?
우선, 이런 좋은 서비스를 만들어주신 개발자님께 감사드립니다!
다음과 같은 버그를 발견하여 이슈를 올리게 되었습니다.

- [ ] isbn이 똑같은 책이 여러 번 나옵니다. 즉, 한 번 보여준 책이 또 나옵니다.

## 📝 어떤 상황에서 발생하나요 ?
1. ["hi" 검색](https://www.bookmoeum.com/search?query=hi)
2. 맨 아래까지 스크롤
3. "로딩 중" 표시 후, 책 정보를 가져올 때

## 💡 기대했던 동작
- [ ] isbn이 다른 책이 나와야 한다고 생각합니다.

제가 잘못 확인했을 수도 있으니, 개발자님의 리뷰가 필요합니다.
읽어주셔서 감사합니다!

##  📷 스크린샷
- **맨 처음 검색했을 때**
![image](https://github.com/user-attachments/assets/877799dc-3bc0-4ef9-b54a-3b216fd581c5)
- **아래까지 스크롤해 첫 번째 로딩 중 후**
![image](https://github.com/user-attachments/assets/5a8de70d-d2d1-4a92-ae35-077eb110a2b4)

**Comment by leechan02** [comment]
축하드려욧...!🎉 입사를 위한 사전과제 테스트였는데, 5000만명 중에 아무도 발견하지 못한걸 발견 하셨습니당!!
바로 채용하겠습니다!!🎉👏

**Comment by gitubanana** [comment]
감사합니다. 힘들게 찾은 보람이 있네요!
언제부터 출근하면 될까요? 사장님!

**Comment by leechan02** [comment]
내일부터 출근해주시면 됩니당!>< 업무는 새로추가된 기능인 내 서재 위시리스트 확인해주시면 됩니당~
24시간 풀타임 근무에 참고로 연봉은 10억입니다:)

**Comment by leechan02** [comment]
1분만에 에러 고침. 감삼니당.❤️

**Comment by gitubanana** [comment]
수고하셨습니다! 사장님.
